version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: "@angular-eslint/eslint-plugin-template"
    versions:
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-eslint/builder"
    versions:
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: electron
    versions:
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
